### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'shortcutsViewMode')

### ISSUE THREAD

**Issue by Alex0007** [cheeaun/phanpy#234]
Dev phanpy

1. publish post
2. click "view published post"

app becomes broken: you can't click any element on the page

```
app.jsx:179 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'shortcutsViewMode')
    at je.ji [as constructor] (app.jsx:179:26)
    at je.sf [as render] (preact.module.js:1:8638)
```

https://github.com/cheeaun/phanpy/assets/1143226/e5418168-1ae8-4e98-ae65-b3b315c12e4a

**Comment by Alex0007** [comment]
I guess it is fixed. Can't reproduce anymore
