### ISSUE TITLE
Uncaught (in promise) ReferenceError: escRef is not defined

### ISSUE THREAD

**Issue by Alex0007** [cheeaun/phanpy#236]
Dev phanpy

1. Click on the user mention in post (example post with mention of user `@darnell`: https://dev.phanpy.social/#/mstdn.social/s/110813096993588536)
1. App becomes broken (all clicks on elements are no longer working)

P.S. Also applicable when clicking on usernames

```
account-sheet.jsx:22 Uncaught (in promise) ReferenceError: escRef is not defined
    at je.vs [as constructor] (account-sheet.jsx:22:12)
    at je.sf [as render] (preact.module.js:1:8638)
```

**Comment by Alex0007** [comment]
Thanks for fix!
