### ISSUE TITLE
Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by Alex0007** [cheeaun/phanpy#343]
Phanpy dev

UI is empty and this error pops in to the console. Tried to relogin – did not helped. 

I think it's related to some specific post in my feed, so it will be hard to reproduce. But it's still worth to catch errors in isMastodonLinkMaybe -> new URL(), i think

```
TypeError: Failed to construct 'URL': Invalid URL
    at ma (isMastodonLinkMaybe.jsx:2:30)
    at status.jsx:1385:49
```

**Comment by Alex0007** [comment]
It struggles with this URL:

```
https://doi.oWIO.1177/1071181322661490
```

That is coming from here


```js
  // Unfurl Mastodon links
  Array.from(
    dom.querySelectorAll(
      'a[href]:not(.u-url):not(.mention):not(.hashtag)',
    ),
  )
 ```

**Comment by Alex0007** [comment]
Thank you for fix!
